// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPbAR1OLLGjJtwmBb60G1MGF5IFiYaatw',
    appId: '1:840156034797:web:1b38daff902982e0983ee4',
    messagingSenderId: '840156034797',
    projectId: 'gorev-yonetim',
    authDomain: 'gorev-yonetim.firebaseapp.com',
    storageBucket: 'gorev-yonetim.appspot.com',
    measurementId: 'G-01M8DNG34D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSw5uHLsyTDZTxS0traZLifcQycMWnlB0',
    appId: '1:840156034797:android:49b21c778ad34787983ee4',
    messagingSenderId: '840156034797',
    projectId: 'gorev-yonetim',
    storageBucket: 'gorev-yonetim.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANhCStIAvpJU6zAVjPRDK-rhyNcsu5Lyg',
    appId: '1:840156034797:ios:70b60bae52681d98983ee4',
    messagingSenderId: '840156034797',
    projectId: 'gorev-yonetim',
    storageBucket: 'gorev-yonetim.appspot.com',
    iosBundleId: 'com.example.gorevYonetim',
  );
}
